Remove caching on reverse_conflicts
We started seeing this in production with memcached usage and the
upgrade to Django 1.5:

    PicklingError: Can't pickle <class 'devel.models.UserProfile_allowed_repos'>: attribute lookup devel.models.UserProfile_allowed_repos failed

Without having time to investigate further, something changed, likely
due to the whole user profile/configurable user model shenanigans done
in Django 1.5. For now, simply don't cache this attribute to work around
the problem.

Signed-off-by: Dan McGee <dan@archlinux.org>