Fix fixture dependency problem in README data loading
django.core.serializers.base.DeserializationError: Problem installing fixture '.../devel/fixtures/staff_groups.json': Group matching query does not exist.

Alphabetical ordering bit us here. Stop cheating in the README and spell
out the fixtures in an order that should work.

Noticed-by: Johannes Löthberg <johannes@kyriasis.com>
Signed-off-by: Dan McGee <dan@archlinux.org>